### PR TITLE
Landing Page update

### PR DESCRIPTION
**Pull request by OlenaPotiatynyk**
## Description

Disable menu for Landing Page

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by mufniarz** [comment]
Hi @OlenaPotiatynyk and @Nyero2023, Though this looks good with the pages we currently have, I'm a little worried that we won't have a way to navigate between a pages once we start adding other pages from ascendynamics.org.  I'm also thinking we may want to keep this part of the menu so that others can find ways to interact with us easier.  Can we connect and discuss.
Screenshot 2024-12-13 at 5 50 11 PM

**Comment by OlenaPotiatynyk** [comment]
@mufniarz and @Nyero2023 I won't be able to meet with you until Tuesday. If you can make a decision before then, please let me know.

**Comment by OlenaPotiatynyk** [comment]
My schedule on Tuesday is quite open. What time slots work best for you?

**Comment by Nyero2023** [comment]
@OlenaPotiatynyk can you do any time between 7 am to 9 am PST?

**Pull request closed without merging**
